"""initial

Revision ID: cff505a9a1bc
Revises: 
Create Date: 2026-07-09 21:48:52.186497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cff505a9a1bc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cbam_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('eori_number', sa.String(length=17), nullable=False),
    sa.Column('declarant_legal_name', sa.String(), nullable=False),
    sa.Column('declarant_address', sa.String(), nullable=False),
    sa.Column('contact_person', sa.String(), nullable=False),
    sa.Column('competent_authority', sa.String(), nullable=False),
    sa.Column('cbam_account_number', sa.String(), nullable=False),
    sa.Column('data_owner', sa.String(), nullable=False),
    sa.Column('taric_code', sa.String(length=10), nullable=False),
    sa.Column('cn_code', sa.String(length=8), nullable=False),
    sa.Column('goods_description', sa.String(), nullable=False),
    sa.Column('sector_category', sa.String(), nullable=False),
    sa.Column('product_type', sa.String(), nullable=False),
    sa.Column('import_volume', sa.Float(), nullable=False),
    sa.Column('date_of_importation', sa.String(), nullable=False),
    sa.Column('country_of_origin', sa.String(), nullable=False),
    sa.Column('customs_declaration_ref', sa.String(), nullable=False),
    sa.Column('supplier_name', sa.String(), nullable=False),
    sa.Column('notes_comments', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cbam_records')
    # ### end Alembic commands ###
